version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    env_file:
      - ../config/.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
      - grafana
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    env_file:
      - ../config/.env
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "5051:80"
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    env_file:
      - ../config/.env
    volumes:
      - redis:/data/redis
    ports:
      - "6380:6379"
    networks:
      - redis
      - grafana
  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    env_file:
      - ../config/.env
    volumes:
      - minio:/data/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data/minio
    networks:
      - minio
      - grafana
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    container_name: grafana
    env_file:
      - ../config/.env
    volumes:
      - grafana:/data/grafana
    ports:
      - "3001:3000"
    networks:
      - grafana
      - loki
  loki:
    image: grafana/loki
    restart: unless-stopped
    container_name: loki
    volumes:
      - ../config/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - grafana
      - loki
      - promtail
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    container_name: promtail
    volumes:
      - ../logs:/home/recipes/logs
      - ../config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - grafana
      - loki
      - promtail
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  minio:
    driver: bridge
  grafana:
    driver: bridge
  loki:
    driver: bridge
  promtail:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
  minio:
  grafana:
  prometheus:
