version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    env_file:
      - ../config/.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin
    env_file:
      - ../config/.env
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "5051:80"
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    env_file:
      - ../config/.env
    volumes:
      - redis:/data/redis
    ports:
      - "6380:6379"
    networks:
      - redis
  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    env_file:
      - ../config/.env
    volumes:
      - minio:/data/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data/minio
    networks:
      - minio
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  minio:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
  minio:
